export const RESERVED_SLUGS = [
  'admin',
  'administrator',
  'auth',
  'login',
  'logout',
  'signup',
  'register',
  'account',
  'accounts',
  'user',
  'users',
  'profile',
  'dashboard',
  'settings',
  'forgot-password',
  'reset-password',
  'verify',
  'verification',
  'api',
  'root',
  'system',
  'sys',
  'mod',
  'moderator',
  'ambassador',
  'status',
  'health',
  'metrics',
  'logs',
  'config',
  'test',
  'dev',
  'staging',
  'null',
  'undefined',
  'shop',
  'store',
  'cart',
  'checkout',
  'product',
  'products',
  'orders',
  'pay',
  'payment',
  'billing',
  'invoice',
  'invoices',
  'pricing',
  'plans',
  'static',
  'assets',
  'public',
  'media',
  'images',
  'css',
  'js',
  'favicon',
  'robots',
  'sitemap',
  'well-known',
  '.well-known',
  'www',
  'mail',
  'webmail',
  'rss',
  'feed',
  'about',
  'contact',
  'terms',
  'privacy',
  'help',
  'support',
  'policy',
  'tos',
  'terms-of-service',
  'privacy-policy'
];

export const isReservedSlug = (slug: string): boolean => {
  if (!slug) return true;

  // ইংরেজি বর্ণ, সংখ্যা এবং হাইফেন ছাড়া অন্য সব ক্যারেক্টার ফিল্টার করা হচ্ছে
  const cleanSlug = slug.trim().toLowerCase().replace(/[^a-z0-9-]/g, '');

  // যদি শুধু স্পেশাল ক্যারেক্টার ($#+&) দেওয়া হয়, তবে cleanSlug খালি ("") হয়ে যাবে।
  // কোনো বৈধ ক্যারেক্টার না থাকলে এটিকে অকার্যকর/সংরক্ষিত ধরে ব্লক (true) করা হবে।
  if (!cleanSlug) return true;

  return RESERVED_SLUGS.includes(cleanSlug);
};
